events { 
    worker_connections 1024; 
}

http {
    # 1. DAFARKAN ALAMAT SERVER BACKEND
    upstream kelompok_web {
        server web1:80;
        server web2:80;
    }

    # 2. ATURAN PINTU MASUK NGXINX
    server {
        listen 80;

        location / {
            # Oper/Teruskan pengunjung ke kelompok_web di atas
            proxy_pass http://kelompok_web;
        }
    }
}
